# Generated by Django 4.0.2 on 2022-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
